version: '3.7'
services:
    db:
      container_name: test-db  
      image: postgres:12.16
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres # Placeholder for sandbox db password
        - POSTGRES_DATABASE=test
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5432:5432'
      volumes: 
        - ./db/psql-data:/var/lib/postgresql/data
        - ./test.sql:/docker-entrypoint-initdb.d/create_tables.sql